import numpy as np
import matplotlib.pyplot as plt

a = np.array([1, 2, 3, 4])
print(a)
b = np.array([[4], [-1], [6]])
print(b)
C = np.array([[3, -2], [7, 1]])
print(C)
D = np.array([[3, -2, 0, 1], [7, 1, -1, 2], [4, -5, 1, 3]])
print(D)
a = np.zeros((1, 2))
print(a)
b = np.ones((4, 1))
print(b)
C = np.eye(3)
print(C)
D = np.eye(3, 4)
print(D)
a = np.array([2, 3, 4])
B = np.array([[1.2, 3.5, 5.1], [-0.3, 1.1, -4.5]])
print(a.shape, a.ndim, a.dtype, a.size)
print(B.shape, B.ndim, B.dtype, B.size)
a = np.array([1, 3, 5, 7, 9, 11])
# a = np.arange(1, 13, 2)
B = np.array([[2, 4, 6], [-1, 5, -3], [0, -2, 3]])
print(a[2: -1])
print(a[:: -1])
print(B[0])
print(B[2, 0])
print(B[1:, 1:])
A = np.array([[1, 3], [-2, 4]])
B = np.array([[2, -1], [3, 0]])
C = np.array([[-2, -5], [1, 3]])
D = np.array([[3, 0], [6, -2]])
E = np.array([[3, 5], [4, -1]])
F = np.array([[-2, 1], [0, -3]])
print(A + B)
print(A - B)
print(C @ D)
print(C.dot(D))
print(E * F)
a = np.array([2, 3, 4])
B = np.array([[1.2, 3.5, 5.1], [-0.3, 1.1, -4.5]])
print(a.reshape(-1, 1))
print(B.T)
A = ([[4, -2], [1, 0]])
print(np.linalg.det(A))
print(np.linalg.inv(A))
print(A @ np.linalg.inv(A))
A = np.array([[4, -2], [1, 0]])
B = np.array([[8, 1, 5], [-3, 0, -7]])
print(A * 0.5)
print(B * 2)
d = np.arange(12)
print(np.reshape(d, (3, 4)))
B = np.array([[2, 4, 6], [-1, 5, -3], [0, -2, 3]])
print(B.max())
print(B.min())
# print(B.min(axis=1))
print(B.sum())
print(B.mean())
print(B.var())
print(B.std())
A = np.array([[0, 1], [2, 4]])
print(np.sqrt(A))
print(np.exp(A))
A = np.array([0, np.pi, np.pi/2, -np.pi/4]).reshape(2, -1)
print(A)
print(np.sin(A))
print(np.cos(A))
A = np.array([[0, 1, -1], [2, 4, -3], [5, -2, 7]])
B = np.array([[-2, 0, 1], [5, -1, 2], [-6, 3, 4]])
C = np.vstack((A, B))
D = np.hstack((A, B))
print(C)
print(D)
print(np.vsplit(C, 2))
print(np.vsplit(C, 3))
print(np.hsplit(D, 2))
x = np.linspace(0, np.pi * 2, 500)
y1 = np.sin(x)
y2 = np.cos(x)
plt.plot(x, y1)
plt.show()
plt.plot(x, y2)
plt.show()
a = np.random.randint(0, 30, size=100)
plt.hist(a)
plt.show()
